/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pastelando_view;

import controller.MenuPrincipalController;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author gsa38
 */
public class MenuPrincipal extends javax.swing.JFrame {
    private final MenuPrincipalController controller;
    /**
     * Creates new form menuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
            Toolkit toolkit = getToolkit();
            Dimension size = toolkit.getScreenSize();
            setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);
        controller = new MenuPrincipalController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardapioButton = new javax.swing.JButton();
        novopedidoButton = new javax.swing.JButton();
        backgroundMenuLabel = new javax.swing.JLabel();
        barraMenuPrincipal = new javax.swing.JMenuBar();
        consultaMenu = new javax.swing.JMenu();
        clienteMenuItem = new javax.swing.JMenuItem();
        pasteisMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");
        setBackground(new java.awt.Color(153, 153, 255));
        setIconImage(Toolkit.getDefaultToolkit().getImage("src/pastelando_imagem/Logo_loginJP.jpg")
        );
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cardapioButton.setBackground(new java.awt.Color(232, 13, 246));
        cardapioButton.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        cardapioButton.setForeground(new java.awt.Color(255, 255, 255));
        cardapioButton.setText("CARDAPIO");
        cardapioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardapioButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cardapioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, 290, 60));

        novopedidoButton.setBackground(new java.awt.Color(229, 14, 244));
        novopedidoButton.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        novopedidoButton.setForeground(new java.awt.Color(255, 255, 255));
        novopedidoButton.setText("NOVO PEDIDO");
        novopedidoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novopedidoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(novopedidoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 290, 60));

        backgroundMenuLabel.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        backgroundMenuLabel.setForeground(new java.awt.Color(255, 255, 255));
        backgroundMenuLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pastelando_imagem/backgroung_Pequeno.jpg"))); // NOI18N
        getContentPane().add(backgroundMenuLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        barraMenuPrincipal.setBackground(new java.awt.Color(229, 14, 244));
        barraMenuPrincipal.setBorder(null);

        consultaMenu.setText("Consultar");

        clienteMenuItem.setText("Clientes");
        clienteMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clienteMenuItemMouseClicked(evt);
            }
        });
        clienteMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteMenuItemActionPerformed(evt);
            }
        });
        consultaMenu.add(clienteMenuItem);

        pasteisMenuItem.setText("Pastéis");
        consultaMenu.add(pasteisMenuItem);

        barraMenuPrincipal.add(consultaMenu);

        setJMenuBar(barraMenuPrincipal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cardapioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardapioButtonActionPerformed
         controller.abrirCardapio();
    }//GEN-LAST:event_cardapioButtonActionPerformed

    private void novopedidoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novopedidoButtonActionPerformed
        controller.abrirNovoPedido();
    }//GEN-LAST:event_novopedidoButtonActionPerformed

    private void clienteMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clienteMenuItemMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteMenuItemMouseClicked

    private void clienteMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteMenuItemActionPerformed
        controller.abrirCliente();
    }//GEN-LAST:event_clienteMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run(){
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundMenuLabel;
    private javax.swing.JMenuBar barraMenuPrincipal;
    private javax.swing.JButton cardapioButton;
    private javax.swing.JMenuItem clienteMenuItem;
    private javax.swing.JMenu consultaMenu;
    private javax.swing.JButton novopedidoButton;
    private javax.swing.JMenuItem pasteisMenuItem;
    // End of variables declaration//GEN-END:variables
}
